/**
 * Extended product catalog — fully-shoppable items with custom Higgsfield
 * product imagery. These are merged into MOCK_PRODUCTS in mock-data.ts
 * via a spread, so they show up everywhere alongside the original entries.
 *
 * Pricing/stock/SKU/fulfillment lives inline here (not in commerce-overlay)
 * because these products are designed for the demo's online ordering flow.
 */

import type { MockProduct } from "./mock-data"
import { BRAND_IMAGES } from "./brand-images"

const PINBALL = BRAND_IMAGES.productPinball
const ARCADE = BRAND_IMAGES.productArcade
const FOOSBALL = BRAND_IMAGES.productFoosball
const AIR_HOCKEY = BRAND_IMAGES.productAirHockey
const PING_PONG = BRAND_IMAGES.productPingPong
const DARTS = BRAND_IMAGES.productDarts
const JUKEBOX = BRAND_IMAGES.productJukebox
const BAR_STOOL = BRAND_IMAGES.productBarStool
const POKER = BRAND_IMAGES.productPoker
const NEON = BRAND_IMAGES.productNeon
const BASKETBALL = BRAND_IMAGES.productBasketball

export const EXTENDED_PRODUCTS: MockProduct[] = [
  // ===== PINBALL =====
  {
    id: "ext-stern-jaws-pro",
    name: "Stern Jaws Pinball — Pro",
    slug: "stern-jaws-pro",
    categorySlug: "games",
    subcategorySlug: "pinball",
    brandName: "Stern",
    imageUrl: PINBALL,
    images: [{ url: PINBALL, alt: "Stern Jaws pinball machine" }],
    description:
      "The Pro edition of Stern's Jaws table — a brand-new theme with three multiball modes, a magnetic shark mech, ramp-fed action, and a backbox display that drops you straight into Amity. Built in Chicago, like every Stern.",
    specifications: {
      type: "Solid-state pinball",
      dimensions: '55"L × 27"W × 75"H',
      weight: "240 lbs",
      power: "120V / 4 Amps",
      warranty: "2-year manufacturer",
      "made in": "Elk Grove Village, IL",
    },
    price: 749900,
    stock: 2,
    sku: "ST-JAWS-PRO",
    fulfillment: ["delivery", "pickup"],
    weightLbs: 240,
    requiresInstall: true,
    addonGroups: ["install", "warranty"],
  },
  {
    id: "ext-stern-foo-fighters-le",
    name: "Stern Foo Fighters Pinball — Limited Edition",
    slug: "stern-foo-fighters-le",
    categorySlug: "games",
    subcategorySlug: "pinball",
    brandName: "Stern",
    imageUrl: PINBALL,
    images: [{ url: PINBALL, alt: "Foo Fighters Limited Edition pinball" }],
    description:
      "The LE treatment — anodized rails, mirrored backglass, custom autographed plaque, integrated subwoofer, and an exclusive shaker motor. 500 units worldwide. The collectible play-it-every-day machine.",
    specifications: {
      type: "Solid-state pinball, LE",
      production: "500 units worldwide",
      audio: "3-channel + subwoofer",
      "shaker motor": "Included",
      autograph: "Hand-signed plaque",
      warranty: "2-year manufacturer",
    },
    price: 1199900,
    stock: 1,
    sku: "ST-FOO-LE",
    fulfillment: ["delivery"],
    weightLbs: 280,
    requiresInstall: true,
    addonGroups: ["install", "warranty"],
  },
  {
    id: "ext-jjp-pirates",
    name: "Jersey Jack Pirates of the Caribbean",
    slug: "jjp-pirates",
    categorySlug: "games",
    subcategorySlug: "pinball",
    brandName: "Jersey Jack Pinball",
    imageUrl: PINBALL,
    images: [{ url: PINBALL, alt: "Jersey Jack Pirates pinball" }],
    description:
      "JJP at its most ambitious — a pirate ship cabinet, tilting upper playfield, a full LCD-style display, and a callout cast of 30+ characters. Long ball times, deep code, the kind of game you keep figuring out for years.",
    specifications: {
      type: "LCD pinball, JJP standard",
      "playfields": "Main + upper drop-down",
      "code depth": "Deep — 30+ characters",
      build: "Lakewood, NJ",
      warranty: "2-year manufacturer",
    },
    price: 999900,
    stock: 1,
    sku: "JJP-POTC",
    fulfillment: ["delivery"],
    weightLbs: 270,
    requiresInstall: true,
    addonGroups: ["install", "warranty"],
  },
  {
    id: "ext-pre-owned-medieval-madness",
    name: "Pre-Owned: Medieval Madness Remake",
    slug: "pre-owned-medieval-madness",
    categorySlug: "games",
    subcategorySlug: "pinball",
    brandName: "Chicago Gaming",
    imageUrl: PINBALL,
    images: [{ url: PINBALL, alt: "Pre-owned Medieval Madness Remake pinball" }],
    description:
      "Restored, shopped, and certified. The CGC Medieval Madness Remake — arguably the greatest pinball ever made, faithfully rebuilt. Plays like new. Comes with our 30-day in-shop warranty.",
    specifications: {
      condition: "Pre-owned, fully restored",
      "shopped by": "ACE Service Bay",
      warranty: "30-day in-shop",
      "play count": "Light home use",
    },
    price: 729900,
    comparePrice: 849900,
    stock: 1,
    sku: "PRE-MM-REMAKE",
    fulfillment: ["delivery", "pickup"],
    weightLbs: 250,
    requiresInstall: true,
    addonGroups: ["install", "warranty"],
  },

  // ===== ARCADE =====
  {
    id: "ext-arcade-classics-multicade",
    name: "Arcade Classics Upright — 412 Games",
    slug: "arcade-classics-multicade-upright",
    categorySlug: "games",
    subcategorySlug: "arcade-games",
    brandName: "Arcade Classics",
    imageUrl: ARCADE,
    images: [{ url: ARCADE, alt: "Multicade arcade upright cabinet" }],
    description:
      "Pac-Man, Galaga, Donkey Kong, Frogger, and 408 more — all licensed, all original ROMs. 19-inch CRT-style LCD, real arcade trackball, two-player joystick + button setup. Plug-and-play out of the box.",
    specifications: {
      games: "412 licensed classics",
      display: '19" LCD with CRT scanline mode',
      controls: "Trackball + 2-player sticks",
      cabinet: "Black laminate, side-art",
      dimensions: '27"W × 32"D × 72"H',
      warranty: "1-year manufacturer",
    },
    price: 449900,
    stock: 4,
    sku: "AC-MC-412",
    fulfillment: ["delivery", "pickup"],
    weightLbs: 220,
    addonGroups: ["accessory", "warranty"],
  },
  {
    id: "ext-arcade1up-streetfighter",
    name: "Arcade1Up Street Fighter II Big Blue",
    slug: "arcade1up-sf2",
    categorySlug: "games",
    subcategorySlug: "arcade-games",
    brandName: "Arcade1Up",
    imageUrl: ARCADE,
    images: [{ url: ARCADE, alt: "Street Fighter II arcade cabinet" }],
    description:
      "The 12-game Capcom collection in a 4-player 'Big Blue' cabinet. SFII Champion Edition, Hyper Fighting, Super Turbo, and the rest. Online play included via WiFi.",
    specifications: {
      games: "12 Capcom classics",
      players: "4 simultaneous",
      "online play": "Included (WiFi)",
      display: '17" LCD',
      cabinet: "Cobalt blue, lit marquee",
    },
    price: 89900,
    stock: 8,
    sku: "A1U-SF2-BB",
    fulfillment: ["pickup", "delivery", "shipping"],
    weightLbs: 110,
    addonGroups: ["warranty"],
  },
  {
    id: "ext-pre-owned-galaga",
    name: "Pre-Owned: Galaga 1981 Original",
    slug: "pre-owned-galaga",
    categorySlug: "games",
    subcategorySlug: "arcade-games",
    brandName: "Namco",
    imageUrl: ARCADE,
    images: [{ url: ARCADE, alt: "Original 1981 Galaga arcade cabinet" }],
    description:
      "An honest-to-god original 1981 Galaga, restored. CRT replaced last year, joysticks rebuilt, full cap kit, original side art touched up. Playing like factory.",
    specifications: {
      year: "1981",
      condition: "Restored",
      "CRT": "Replaced 2024",
      "side art": "Original, touched up",
      warranty: "30-day in-shop",
    },
    price: 329900,
    stock: 1,
    sku: "PRE-GALAGA-81",
    fulfillment: ["delivery", "pickup"],
    weightLbs: 195,
    addonGroups: ["warranty"],
  },

  // ===== FOOSBALL =====
  {
    id: "ext-tornado-elite-foosball",
    name: "Tornado Elite Tournament Foosball",
    slug: "tornado-elite-foosball",
    categorySlug: "games",
    subcategorySlug: "foosball",
    brandName: "Tornado",
    imageUrl: FOOSBALL,
    images: [{ url: FOOSBALL, alt: "Tornado Elite tournament foosball table" }],
    description:
      "The official table of the USTSA Tour. Steel rods, counter-balanced players, end-loading goal box, leveling feet. Tournament-grade — and tough enough for the basement.",
    specifications: {
      players: "Counterbalanced, USTSA-spec",
      rods: "Heat-treated, hollow steel",
      goal: "End-loading, scoring abacus",
      surface: "1-piece poly",
      build: "Made in Texas",
    },
    price: 199900,
    stock: 3,
    sku: "TRN-ELITE-FB",
    fulfillment: ["delivery", "pickup"],
    weightLbs: 380,
    addonGroups: ["accessory", "warranty"],
  },
  {
    id: "ext-warrior-pro-foosball",
    name: "Warrior Pro Foosball",
    slug: "warrior-pro-foosball",
    categorySlug: "games",
    subcategorySlug: "foosball",
    brandName: "Warrior",
    imageUrl: FOOSBALL,
    images: [{ url: FOOSBALL, alt: "Warrior Pro foosball table" }],
    description:
      "Warrior's flagship — black PVD-coated rods, custom counterweighted men, three balls in the goal cup. Slightly faster than a Tornado, slightly cheaper. The competitive choice.",
    specifications: {
      rods: "PVD-coated steel",
      players: "Counterweighted",
      finish: "Matte black",
      "balls included": "3 balls + 6 spares",
    },
    price: 159900,
    stock: 4,
    sku: "WRR-PRO-FB",
    fulfillment: ["delivery", "pickup", "shipping"],
    weightLbs: 320,
    addonGroups: ["accessory", "warranty"],
  },

  // ===== AIR HOCKEY =====
  {
    id: "ext-dynamo-pro-air-hockey",
    name: "Dynamo Pro 8' Air Hockey",
    slug: "dynamo-pro-air-hockey",
    categorySlug: "games",
    subcategorySlug: "air-hockey",
    brandName: "Dynamo",
    imageUrl: AIR_HOCKEY,
    images: [{ url: AIR_HOCKEY, alt: "Dynamo Pro 8 foot air hockey table" }],
    description:
      "Commercial-grade air hockey — the kind that lives in arcades. ⅛-inch aluminum playing surface, dual blowers, electronic scoring, overhead lights with LED accents.",
    specifications: {
      surface: '⅛" aluminum, perforated',
      blowers: "Dual, commercial-grade",
      scoring: "Electronic, overhead",
      length: "8 feet",
      warranty: "5-year on motor, 1-year overall",
    },
    price: 249900,
    stock: 2,
    sku: "DYN-PRO-8AH",
    fulfillment: ["delivery", "pickup"],
    weightLbs: 350,
    addonGroups: ["warranty"],
  },
  {
    id: "ext-atomic-blazer-air-hockey",
    name: "Atomic Blazer 7' Air Hockey",
    slug: "atomic-blazer-air-hockey",
    categorySlug: "games",
    subcategorySlug: "air-hockey",
    brandName: "Atomic",
    imageUrl: AIR_HOCKEY,
    images: [{ url: AIR_HOCKEY, alt: "Atomic Blazer 7 foot air hockey table" }],
    description:
      "The home-friendly 7-foot version — same fast surface, slightly smaller footprint. Strong blower, bright rail lighting, electronic puck-drop on goals. Family room ready.",
    specifications: {
      length: "7 feet",
      surface: "Tempered slick",
      lights: "LED rail accent",
      scoring: "Electronic",
      warranty: "1-year",
    },
    price: 119900,
    stock: 5,
    sku: "ATM-BLZ-7AH",
    fulfillment: ["delivery", "pickup", "shipping"],
    weightLbs: 245,
    addonGroups: ["warranty"],
  },

  // ===== PING PONG =====
  {
    id: "ext-stiga-pro-carbon-pp",
    name: "STIGA Pro Carbon Tournament Table",
    slug: "stiga-pro-carbon",
    categorySlug: "games",
    subcategorySlug: "ping-pong",
    brandName: "STIGA",
    imageUrl: PING_PONG,
    images: [{ url: PING_PONG, alt: "STIGA Pro Carbon ping pong table" }],
    description:
      "ITTF-approved 25mm playing surface — the standard at sanctioned tournaments. Folds in half for storage, locking casters, integrated paddle and ball storage.",
    specifications: {
      surface: "25mm, ITTF-approved",
      "fold-up": "Yes — single half play mode",
      casters: "Locking",
      "paddle storage": "Integrated drawer",
    },
    price: 99900,
    stock: 6,
    sku: "STG-PRO-CRB",
    fulfillment: ["delivery", "pickup", "shipping"],
    weightLbs: 200,
    addonGroups: ["accessory", "warranty"],
  },
  {
    id: "ext-killerspin-myt7",
    name: "Killerspin MyT7 Outdoor Table",
    slug: "killerspin-myt7",
    categorySlug: "games",
    subcategorySlug: "ping-pong",
    brandName: "Killerspin",
    imageUrl: PING_PONG,
    images: [{ url: PING_PONG, alt: "Killerspin MyT7 outdoor table" }],
    description:
      "Aluminum-composite top that won't warp in the rain. Steel frame, locking wheels. Made for the patio that's actually used.",
    specifications: {
      surface: "Aluminum composite",
      "outdoor rated": "Yes — UV + waterproof",
      frame: "Powder-coated steel",
    },
    price: 79900,
    stock: 4,
    sku: "KSP-MYT7",
    fulfillment: ["delivery", "shipping"],
    weightLbs: 175,
    addonGroups: ["accessory", "warranty"],
  },

  // ===== DARTS =====
  {
    id: "ext-winmau-blade-cabinet",
    name: "Winmau Blade 6 Bristle Set + Cabinet",
    slug: "winmau-blade-set",
    categorySlug: "games",
    subcategorySlug: "darts",
    brandName: "Winmau",
    imageUrl: DARTS,
    images: [{ url: DARTS, alt: "Winmau Blade dartboard with cabinet" }],
    description:
      "The board played in the PDC World Darts Championship. Plus a furniture-grade oak cabinet to mount it in. Score chalkboards on the doors. Full setup ready to hang.",
    specifications: {
      board: "Winmau Blade 6 — PDC official",
      cabinet: "Solid oak, 6 darts included",
      "scoring": "Dual chalkboard doors",
      "darts included": "6 steel-tip starter set",
    },
    price: 39900,
    stock: 8,
    sku: "WIN-BLD-CAB",
    fulfillment: ["pickup", "delivery", "shipping"],
    weightLbs: 35,
    addonGroups: ["accessory"],
  },
  {
    id: "ext-arachnid-electronic-dart",
    name: "Arachnid Cricket Pro 800 Electronic",
    slug: "arachnid-cricket-pro-800",
    categorySlug: "games",
    subcategorySlug: "darts",
    brandName: "Arachnid",
    imageUrl: DARTS,
    images: [{ url: DARTS, alt: "Arachnid electronic dartboard" }],
    description:
      "Electronic scoring with NylaTech segments — quieter than competitors, longer-lasting. 39 games, online play (Bullshooter Live), 8-player support, soft-tip safe.",
    specifications: {
      type: "Soft-tip electronic",
      games: "39 + variants",
      players: "Up to 8",
      online: "Bullshooter Live network",
      power: "AC adapter included",
    },
    price: 24900,
    stock: 6,
    sku: "ARC-CKT-800",
    fulfillment: ["pickup", "delivery", "shipping"],
    weightLbs: 14,
    addonGroups: ["accessory"],
  },

  // ===== JUKEBOX =====
  {
    id: "ext-rock-ola-bubbler",
    name: "Rock-Ola Bubbler Music Center CD",
    slug: "rock-ola-bubbler-cd",
    categorySlug: "games",
    subcategorySlug: "jukebox",
    brandName: "Rock-Ola",
    imageUrl: JUKEBOX,
    images: [{ url: JUKEBOX, alt: "Rock-Ola Bubbler jukebox" }],
    description:
      "The reborn 1948 'Bubbler' — bubble tubes glowing, chrome arches, walnut cabinet. Modern internals: 100 CD changer + Bluetooth + 1000-watt amp. The centerpiece your basement deserves.",
    specifications: {
      style: "1948 Bubbler reissue",
      capacity: "100 CDs + Bluetooth",
      amp: "1000W",
      "bubble tubes": "Animated",
      cabinet: "Solid walnut + chrome",
    },
    price: 949900,
    stock: 1,
    sku: "RKO-BUB-CD",
    fulfillment: ["delivery"],
    weightLbs: 320,
    requiresInstall: true,
    addonGroups: ["install", "warranty"],
  },
  {
    id: "ext-crosley-vinyl-jukebox",
    name: "Crosley Rocket 200 Disc Jukebox",
    slug: "crosley-rocket-200",
    categorySlug: "games",
    subcategorySlug: "jukebox",
    brandName: "Crosley",
    imageUrl: JUKEBOX,
    images: [{ url: JUKEBOX, alt: "Crosley Rocket 200 disc jukebox" }],
    description:
      "Smaller, gentler on the wallet — Crosley's 200-disc CD jukebox with retro chrome trim and color-changing LED accents. Perfect for the basement that doesn't quite need a full Wurlitzer.",
    specifications: {
      capacity: "200 CDs",
      LEDs: "Color-changing trim",
      audio: "Stereo, 2x40W",
      controls: "Front-panel + remote",
    },
    price: 129900,
    stock: 3,
    sku: "CRS-RKT-200",
    fulfillment: ["delivery", "pickup", "shipping"],
    weightLbs: 95,
    addonGroups: ["accessory", "warranty"],
  },

  // ===== BAR STOOLS =====
  {
    id: "ext-callee-cosmo-stool",
    name: "Callee Cosmo Swivel Bar Stool",
    slug: "callee-cosmo-stool",
    categorySlug: "furniture",
    subcategorySlug: "bar-stools",
    brandName: "Callee",
    imageUrl: BAR_STOOL,
    images: [{ url: BAR_STOOL, alt: "Callee Cosmo bar stool in oxblood leather" }],
    description:
      "Hand-crafted in California — solid hardwood frame, full-grain leather seat, brass nailhead trim, 360° swivel with memory return. Ten upholstery options, three wood finishes. The stool you'll have for thirty years.",
    specifications: {
      frame: "Solid hardwood",
      upholstery: "Full-grain leather (10 options)",
      swivel: "360°, memory return",
      "seat height": "26\" or 30\"",
      warranty: "Lifetime frame",
      "made in": "Riverside, CA",
    },
    price: 89900,
    stock: 12,
    sku: "CAL-CSM-LTHR",
    fulfillment: ["pickup", "delivery", "shipping"],
    weightLbs: 38,
    addonGroups: ["pairing", "warranty"],
  },
  {
    id: "ext-darafeev-mocha-stool",
    name: "Darafeev Mocha Counter Stool",
    slug: "darafeev-mocha-stool",
    categorySlug: "furniture",
    subcategorySlug: "bar-stools",
    brandName: "Darafeev",
    imageUrl: BAR_STOOL,
    images: [{ url: BAR_STOOL, alt: "Darafeev Mocha counter stool" }],
    description:
      "Illinois-made by the Darafeev family since 1946. Solid maple, hand-rubbed mocha finish, contoured seat that fits how you actually sit. Counter or bar height — your call.",
    specifications: {
      wood: "Solid maple",
      finish: "Hand-rubbed mocha",
      heights: 'Counter (24") or Bar (30")',
      warranty: "Lifetime frame",
      "made in": "Cary, IL",
    },
    price: 69900,
    stock: 15,
    sku: "DRA-MCH-STL",
    fulfillment: ["pickup", "delivery", "shipping"],
    weightLbs: 32,
    addonGroups: ["pairing", "warranty"],
  },
  {
    id: "ext-holland-bar-stool-co-classic",
    name: "Holland Bar Stool Co. Classic Wood",
    slug: "holland-classic-stool",
    categorySlug: "furniture",
    subcategorySlug: "bar-stools",
    brandName: "Holland Bar Stool Co.",
    imageUrl: BAR_STOOL,
    images: [{ url: BAR_STOOL, alt: "Holland Bar Stool classic wood stool" }],
    description:
      "Made in Holland, MI. Hardwood ladder back or barrel design, customizable seat — fabric, vinyl, or full-grain leather, pick your school colors or pattern. Sturdy enough for your brother-in-law.",
    specifications: {
      frame: "Solid hardwood (oak/maple)",
      "seat options": "Fabric / vinyl / leather, custom",
      heights: 'Counter (25") or Bar (30")',
      warranty: "5-year frame",
      "made in": "Holland, MI",
    },
    price: 39900,
    stock: 20,
    sku: "HBS-CLS-WD",
    fulfillment: ["pickup", "delivery", "shipping"],
    weightLbs: 26,
    addonGroups: ["pairing", "warranty"],
  },

  // ===== POKER =====
  {
    id: "ext-presidential-octagon-poker",
    name: "Presidential Octagon Poker Table",
    slug: "presidential-octagon-poker",
    categorySlug: "furniture",
    subcategorySlug: "poker-tables",
    brandName: "Presidential Billiards",
    imageUrl: POKER,
    images: [{ url: POKER, alt: "Presidential octagon poker table" }],
    description:
      "Eight-player octagonal table with rich green felt, leather-padded armrest, eight chip cup wells, and a removable dining-conversion top. Walnut frame, hand-crafted in North Carolina.",
    specifications: {
      players: "8",
      shape: "Octagonal",
      surface: "Tournament green felt",
      "cup wells": "8 brass-rimmed",
      "dining conversion": "Included",
      "made in": "Hickory, NC",
    },
    price: 489900,
    stock: 2,
    sku: "PRS-OCT-PKR",
    fulfillment: ["delivery", "pickup"],
    weightLbs: 240,
    addonGroups: ["warranty"],
  },
  {
    id: "ext-rangertec-folding-poker",
    name: "RangerTec Folding Poker Top (8-Player)",
    slug: "rangertec-folding-poker-top",
    categorySlug: "furniture",
    subcategorySlug: "poker-tables",
    brandName: "RangerTec",
    imageUrl: POKER,
    images: [{ url: POKER, alt: "RangerTec folding poker top" }],
    description:
      "The poker top that lives under your couch. Fold-out 8-position octagon, vinyl rail, suede playing field, fits over any 4-foot table. Brings home-game night without the furniture commitment.",
    specifications: {
      players: "8",
      type: "Folding poker top (table not included)",
      surface: "Suede + vinyl rail",
      "fits over": "Standard 48\"+ tables",
    },
    price: 17900,
    stock: 8,
    sku: "RNG-FLD-8P",
    fulfillment: ["pickup", "delivery", "shipping"],
    weightLbs: 28,
    addonGroups: ["accessory"],
  },

  // ===== NEONS =====
  {
    id: "ext-neon-pool-hall",
    name: "Custom Neon: Pool Hall Sign",
    slug: "neon-pool-hall",
    categorySlug: "furniture",
    subcategorySlug: "neons",
    brandName: "ACE Custom",
    imageUrl: NEON,
    images: [{ url: NEON, alt: "Custom pool hall neon sign" }],
    description:
      "Glass-bent in Chicago. Two-color amber + red neon spelling 'POOL HALL' with a stylized 9-ball. Plug-and-play 110V, hangs from chain or wall mounts. The basement centerpiece.",
    specifications: {
      colors: "Amber + Red (two-color)",
      size: '36"W × 18"H',
      power: "110V plug, ~25W",
      "hang options": "Chain or wall mount",
      "glass-bent in": "Chicago",
    },
    price: 49900,
    stock: 5,
    sku: "ACE-NEON-PH",
    fulfillment: ["pickup", "delivery", "shipping"],
    weightLbs: 12,
  },
  {
    id: "ext-neon-game-room",
    name: "Custom Neon: 'Game Room' Script",
    slug: "neon-game-room",
    categorySlug: "furniture",
    subcategorySlug: "neons",
    brandName: "ACE Custom",
    imageUrl: NEON,
    images: [{ url: NEON, alt: "Game Room neon sign in cursive" }],
    description:
      "Cursive 'Game Room' in warm orange neon. Cleaner, more modern than the classic pub-style signs. Looks at home above a bar or behind a billiard table.",
    specifications: {
      colors: "Warm orange",
      size: '40"W × 12"H',
      power: "110V plug",
      style: "Modern cursive",
    },
    price: 32900,
    stock: 7,
    sku: "ACE-NEON-GR",
    fulfillment: ["pickup", "delivery", "shipping"],
    weightLbs: 10,
  },

  // ===== BASKETBALL GOALS =====
  {
    id: "ext-goalsetter-mvp-72",
    name: 'Goalsetter MVP 72" In-Ground Basketball Goal',
    slug: "goalsetter-mvp-72",
    categorySlug: "outdoor",
    subcategorySlug: "basketball-goals",
    brandName: "Goalsetter",
    imageUrl: BASKETBALL,
    images: [{ url: BASKETBALL, alt: "Goalsetter MVP 72-inch basketball goal" }],
    description:
      'Regulation 72" tempered glass backboard, breakaway HD rim, in-ground anchor system that lets you swap heights from 7.5\' to 10\'. The endgame goal — install once, never replace.',
    specifications: {
      backboard: '72" tempered glass, regulation',
      rim: "Breakaway HD",
      "height adjust": "7.5' to 10'",
      anchor: "In-ground (cement included)",
      warranty: "Lifetime",
      "made in": "Sioux Falls, SD",
    },
    price: 224900,
    stock: 3,
    sku: "GST-MVP-72",
    fulfillment: ["delivery"],
    weightLbs: 410,
    requiresInstall: true,
    addonGroups: ["install", "warranty"],
  },
  {
    id: "ext-lifetime-portable-54",
    name: 'Lifetime 54" Portable Adjustable Basketball Hoop',
    slug: "lifetime-portable-54",
    categorySlug: "outdoor",
    subcategorySlug: "basketball-goals",
    brandName: "Lifetime",
    imageUrl: BASKETBALL,
    images: [{ url: BASKETBALL, alt: "Lifetime 54-inch portable basketball hoop" }],
    description:
      'The portable that doesn\'t feel portable. 54" polycarbonate backboard, height-adjustable from 7.5\' to 10\', water-fillable base for stability, two transport wheels.',
    specifications: {
      backboard: '54" polycarbonate',
      "height adjust": "7.5' to 10'",
      base: "Sand or water filled",
      "transport wheels": "Yes",
      warranty: "5-year",
    },
    price: 64900,
    stock: 6,
    sku: "LF-PRT-54",
    fulfillment: ["delivery", "shipping"],
    weightLbs: 165,
    addonGroups: ["install", "warranty"],
  },

  // ===== TRAMPOLINES =====
  {
    id: "ext-springfree-jumbo-square",
    name: "Springfree Jumbo Square Trampoline",
    slug: "springfree-jumbo-square",
    categorySlug: "outdoor",
    subcategorySlug: "trampolines",
    brandName: "Springfree",
    imageUrl: BASKETBALL,
    images: [{ url: BASKETBALL, alt: "Springfree Jumbo Square trampoline" }],
    description:
      "The world's only trampoline with no exposed springs. Composite rods flex below the jumping mat — kids can't pinch fingers, miss the mat, or hit a frame. Comes with FlexrHoop and tgoma games available.",
    specifications: {
      shape: "Square — 13' × 13'",
      springs: "None — flexible composite rods",
      "weight limit": "330 lbs",
      "soft-edge mat": "Yes",
      warranty: "10-year mat, lifetime frame",
    },
    price: 269900,
    stock: 2,
    sku: "SF-JMB-SQ",
    fulfillment: ["delivery", "shipping"],
    weightLbs: 320,
    requiresInstall: true,
    addonGroups: ["install", "warranty"],
  },
  {
    id: "ext-springfree-medium-oval",
    name: "Springfree Medium Oval Trampoline",
    slug: "springfree-medium-oval",
    categorySlug: "outdoor",
    subcategorySlug: "trampolines",
    brandName: "Springfree",
    imageUrl: BASKETBALL,
    images: [{ url: BASKETBALL, alt: "Springfree Medium Oval trampoline" }],
    description:
      "8x11 oval — the right size for two kids without dominating the yard. Same springless engineering, same lifetime frame warranty.",
    specifications: {
      shape: "Oval — 8' × 11'",
      springs: "None — flexible composite rods",
      "weight limit": "300 lbs",
      warranty: "10-year mat, lifetime frame",
    },
    price: 189900,
    stock: 4,
    sku: "SF-MED-OVAL",
    fulfillment: ["delivery", "shipping"],
    weightLbs: 245,
    addonGroups: ["install", "warranty"],
  },

  // ===== BUMPER POOL =====
  {
    id: "ext-cl-bailey-bumper-pool",
    name: "C.L. Bailey 7-Star Bumper Pool",
    slug: "cl-bailey-bumper-pool",
    categorySlug: "games",
    subcategorySlug: "bumper-pool",
    brandName: "C.L. Bailey",
    imageUrl: PING_PONG,
    images: [{ url: PING_PONG, alt: "C.L. Bailey bumper pool table" }],
    description:
      "The bumper pool table the rest are knockoffs of. Solid hardwood frame, regulation cushions, 8 metal bumper posts, two-pocket scoring, includes cues + balls.",
    specifications: {
      type: "Bumper pool",
      players: "2",
      bumpers: "8 metal posts",
      "balls included": "Red & white set",
      "cues included": "2 short cues",
    },
    price: 169900,
    stock: 2,
    sku: "CLB-7STR-BP",
    fulfillment: ["delivery", "pickup"],
    weightLbs: 220,
    addonGroups: ["accessory", "warranty"],
  },
]
